---
abstract: 'assign resources using the same algorithm used by men choosing which urinal to use'
author:
  - 'Sterling Hanenkamp'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Urinal
version: 1.0
